ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS cancelled BOOLEAN;

UPDATE orders
SET cancelled = CASE
  WHEN status = 'cancelled' THEN TRUE
  ELSE FALSE
END
WHERE cancelled IS NULL;

ALTER TABLE orders
  ALTER COLUMN cancelled SET NOT NULL,
  ALTER COLUMN cancelled SET DEFAULT FALSE;

ALTER TABLE orders
  DROP COLUMN IF EXISTS status;

